.TH "Содержание директории src/core" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src/core
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBconfig\&.hpp\fP"
.br
.ti -1c
.RI "файл \fBenviroment\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBenviroment\&.hpp\fP"
.br
.ti -1c
.RI "файл \fBrun\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBrun\&.hpp\fP"
.br
.in -1c
