.TH "Содержание директории src/control" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории src/control
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBmove\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBmove\&.hpp\fP"
.br
.ti -1c
.RI "файл \fBquit\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBquit\&.hpp\fP"
.br
.in -1c
