.TH "src/hardware/distancesensor.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hardware/distancesensor.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include 'core/config\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmosh::hardware::DistanceSensor\fP"
.br
.RI "Интерфейс датчика растояния "
.ti -1c
.RI "class \fBmosh::hardware::NoDistanceSensor\fP"
.br
.RI "Заглушка "
.ti -1c
.RI "class \fBmosh::hardware::IrSensorSharp\fP"
.br
.RI "Инфокрасный датчик Sharp\&. "
.ti -1c
.RI "class \fBmosh::hardware::UltraSonic\fP"
.br
.RI "УльтраЗвуковой датчик HC SR04\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::hardware\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
