.TH "src/core/enviroment.cpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/enviroment.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'enviroment\&.hpp'\fP
.br

.SS "Переменные"

.in +1c
.ti -1c
.RI "\fBmosh::hardware::LineSensor\fP \fBlineL\fP (\fBLINE_L\fP, \fBL_LINE\fP, \fBL_FIELD\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::LineSensor\fP \fBlineR\fP (\fBLINE_R\fP, \fBR_LINE\fP, \fBR_FIELD\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::NoDistanceSensor\fP \fBno_sensor\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::IrSensorSharp\fP \fBir0\fP (\fBIR_0\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::IrSensorSharp\fP \fBir1\fP (\fBIR_1\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::UltraSonic\fP \fBus\fP (\fBUS_ECHO\fP, \fBUS_TRIG\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::MotorEncoder\fP \fBmotorL\fP (\fBmosh::hardware::__l_int\fP, \fBMOTOR_L_INVERT\fP, \fBMOTOR_L_SPEED\fP, \fBMOTOR_L_DIR\fP, \fBMOTOR_L_ENC_A\fP, \fBMOTOR_L_ENC_B\fP)"
.br
.ti -1c
.RI "\fBmosh::hardware::MotorEncoder\fP \fBmotorR\fP (\fBmosh::hardware::__r_int\fP, \fBMOTOR_R_INVERT\fP, \fBMOTOR_R_SPEED\fP, \fBMOTOR_R_DIR\fP, \fBMOTOR_R_ENC_A\fP, \fBMOTOR_R_ENC_B\fP)"
.br
.ti -1c
.RI "\fBRobotConfig\fP \fBrobot\fP"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "\fBmosh::hardware::IrSensorSharp\fP ir0(\fBIR_0\fP) (\fBIR_0\fP)"

.SS "\fBmosh::hardware::IrSensorSharp\fP ir1(\fBIR_1\fP) (\fBIR_1\fP)"

.SS "\fBmosh::hardware::LineSensor\fP lineL(\fBLINE_L\fP, \fBL_LINE\fP, \fBL_FIELD\fP) (\fBLINE_L\fP, \fBL_LINE\fP, \fBL_FIELD\fP)"

.SS "\fBmosh::hardware::LineSensor\fP lineR(\fBLINE_R\fP, \fBR_LINE\fP, \fBR_FIELD\fP) (\fBLINE_R\fP, \fBR_LINE\fP, \fBR_FIELD\fP)"

.SS "\fBmosh::hardware::MotorEncoder\fP motorL(\fBmosh::hardware::__l_int\fP, \fBMOTOR_L_INVERT\fP, \fBMOTOR_L_SPEED\fP, \fBMOTOR_L_DIR\fP, \fBMOTOR_L_ENC_A\fP, \fBMOTOR_L_ENC_B\fP) (\fBmosh::hardware::__l_int\fP, \fBMOTOR_L_INVERT\fP, \fBMOTOR_L_SPEED\fP, \fBMOTOR_L_DIR\fP, \fBMOTOR_L_ENC_A\fP, \fBMOTOR_L_ENC_B\fP)"

.SS "\fBmosh::hardware::MotorEncoder\fP motorR(\fBmosh::hardware::__r_int\fP, \fBMOTOR_R_INVERT\fP, \fBMOTOR_R_SPEED\fP, \fBMOTOR_R_DIR\fP, \fBMOTOR_R_ENC_A\fP, \fBMOTOR_R_ENC_B\fP) (\fBmosh::hardware::__r_int\fP, \fBMOTOR_R_INVERT\fP, \fBMOTOR_R_SPEED\fP, \fBMOTOR_R_DIR\fP, \fBMOTOR_R_ENC_A\fP, \fBMOTOR_R_ENC_B\fP)"

.SS "\fBmosh::hardware::NoDistanceSensor\fP no_sensor"

.SS "\fBRobotConfig\fP robot"

.SS "\fBmosh::hardware::UltraSonic\fP us(\fBUS_ECHO\fP, \fBUS_TRIG\fP) (\fBUS_ECHO\fP, \fBUS_TRIG\fP)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
