.TH "src/core/enviroment.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/enviroment.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'hardware/distancesensor\&.hpp'\fP
.br
\fR#include 'hardware/linesensor\&.hpp'\fP
.br
\fR#include 'hardware/motorencoder\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "struct \fBRobotConfig\fP"
.br
.RI "Данные робота "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmotors\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBmotors::reset\fP ()"
.br
.ti -1c
.RI "void \fBmotors::spin\fP ()"
.br
.ti -1c
.RI "void \fBmotors::setSpeeds\fP (int16_t left, int16_t right)"
.br
.ti -1c
.RI "void \fBmotors::setForTicks\fP (int8_t speed_L, int32_t ticks_L, int8_t speed_R, int32_t ticks_R)"
.br
.in -1c
.SS "Переменные"

.in +1c
.ti -1c
.RI "\fBmosh::hardware::LineSensor\fP \fBlineL\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::LineSensor\fP \fBlineR\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::NoDistanceSensor\fP \fBno_sensor\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::IrSensorSharp\fP \fBir0\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::IrSensorSharp\fP \fBir1\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::UltraSonic\fP \fBus\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::MotorEncoder\fP \fBmotorL\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::MotorEncoder\fP \fBmotorR\fP"
.br
.ti -1c
.RI "\fBRobotConfig\fP \fBrobot\fP"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "\fBmosh::hardware::IrSensorSharp\fP ir0\fR [extern]\fP"

.SS "\fBmosh::hardware::IrSensorSharp\fP ir1\fR [extern]\fP"

.SS "\fBmosh::hardware::LineSensor\fP lineL\fR [extern]\fP"

.SS "\fBmosh::hardware::LineSensor\fP lineR\fR [extern]\fP"

.SS "\fBmosh::hardware::MotorEncoder\fP motorL\fR [extern]\fP"

.SS "\fBmosh::hardware::MotorEncoder\fP motorR\fR [extern]\fP"

.SS "\fBmosh::hardware::NoDistanceSensor\fP no_sensor\fR [extern]\fP"

.SS "\fBRobotConfig\fP robot\fR [extern]\fP"

.SS "\fBmosh::hardware::UltraSonic\fP us\fR [extern]\fP"

.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
