.TH "src/hardware/linesensor.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hardware/linesensor.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include 'core/config\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmosh::hardware::LineSensor\fP"
.br
.RI "Аналоговый датчик линии "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::hardware\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
