.TH "mosh::control::Quiter" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mosh::control::Quiter \- Интерфейс обработки завершения движения  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <quit\&.hpp>\fP
.PP
Производные классы:\fBmosh::control::DistanceMoved\fP, \fBmosh::control::DistanceRead\fP, \fBmosh::control::LineFound\fP и \fBmosh::control::OnTimer\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual bool \fBtick\fP () const =0"
.br
.RI "Обработка события "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс обработки завершения движения 
.SH "Методы"
.PP 
.SS "virtual bool mosh::control::Quiter::tick () const\fR [pure virtual]\fP"

.PP
Обработка события 
.PP
\fBВозвращает\fP
.RS 4
true если ещё НЕ вышел, false когда следует прервать работу 
.RE
.PP

.PP
Замещается в \fBmosh::control::OnTimer\fP, \fBmosh::control::DistanceRead\fP, \fBmosh::control::DistanceMoved\fP и \fBmosh::control::LineFound\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
