.TH "mosh::hardware::UltraSonic" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mosh::hardware::UltraSonic \- УльтраЗвуковой датчик HC SR04\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <distancesensor\&.hpp>\fP
.PP
Базовые классы:\fBmosh::hardware::DistanceSensor\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBUltraSonic\fP (uint8_t pin_echo, uint8_t pin_trig)"
.br
.RI "Ультразвуковой датчик расстояния "
.in -1c

Открытые члены унаследованные от \fBmosh::hardware::DistanceSensor\fP
.in +1c
.ti -1c
.RI "\fBDistanceSensor\fP (uint16_t min_dist, uint16_t max_dist, uint8_t period)"
.br
.RI "Абстрактный Датчик расстояния "
.ti -1c
.RI "uint8_t \fBread\fP () const"
.br
.RI "Получить значение с датчика "
.ti -1c
.RI "uint8_t \fBoperator()\fP () const"
.br
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "uint8_t \fBupdate\fP () const override"
.br
.RI "Опросить датчик "
.in -1c
.SH "Подробное описание"
.PP 
УльтраЗвуковой датчик HC SR04\&. 
.SH "Конструктор(ы)"
.PP 
.SS "UltraSonic::UltraSonic (uint8_t pin_echo, uint8_t pin_trig)"

.PP
Ультразвуковой датчик расстояния 
.PP
\fBАргументы\fP
.RS 4
\fIpin_echo\fP Пин приёма 
.br
\fIpin_trig\fP Пин Триггера 
.RE
.PP
.PP
.nf
33                                                                      :
34     DistanceSensor(PARAMS::US_DIST_MIN, PARAMS::US_DIST_MAX, PARAMS::US_PERIOD), PIN_ECHO(pin_echo), PIN_TRIG(pin_trig) {
35     pinMode(PIN_ECHO, INPUT);
36     pinMode(PIN_TRIG, OUTPUT);
37 }
.fi

.SH "Методы"
.PP 
.SS "uint8_t UltraSonic::update () const\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.PP
Опросить датчик 
.PP
\fBВозвращает\fP
.RS 4
значение расстояние в мм 
.RE
.PP

.PP
Замещает \fBmosh::hardware::DistanceSensor\fP\&..PP
.nf
39                                  {
40     digitalWrite(PIN_TRIG, LOW);
41     delayMicroseconds(5);
42     digitalWrite(PIN_TRIG, HIGH);
43     delayMicroseconds(15);
44     digitalWrite(PIN_TRIG, LOW);
45     uint32_t d = pulseIn(PIN_ECHO, HIGH);
46     return d / (2 * 29\&.1);
47 }
.fi


.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
