.TH "mosh::control" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mosh::control
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBDistanceMoved\fP"
.br
.RI "Было пройдено расстояние "
.ti -1c
.RI "class \fBDistanceRead\fP"
.br
.RI "Обработка расстояния "
.ti -1c
.RI "class \fBKeepSpeed\fP"
.br
.RI "режим постоянной скорости "
.ti -1c
.RI "class \fBLineFound\fP"
.br
.RI "Найден перекрёсток "
.ti -1c
.RI "class \fBLineProp\fP"
.br
.RI "Пропорциональный регулятор движения по линии "
.ti -1c
.RI "class \fBLineRelay\fP"
.br
.ti -1c
.RI "class \fBLineRelay2\fP"
.br
.RI "Релейный регулятор движения по линии по двум датчикам "
.ti -1c
.RI "class \fBMoveAlongWall\fP"
.br
.ti -1c
.RI "class \fBMover\fP"
.br
.RI "Абстрактный исполнитель движения робота "
.ti -1c
.RI "class \fBOnTimer\fP"
.br
.RI "Обработка выхода по таймеру "
.ti -1c
.RI "class \fBQuiter\fP"
.br
.RI "Интерфейс обработки завершения движения "
.ti -1c
.RI "class \fBSync\fP"
.br
.RI "Синхронизированое движение моторов "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
