.TH "mosh::control::Mover" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mosh::control::Mover \- Абстрактный исполнитель движения робота  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <move\&.hpp>\fP
.PP
Производные классы:\fBmosh::control::KeepSpeed\fP, \fBmosh::control::LineProp\fP, \fBmosh::control::LineRelay\fP, \fBmosh::control::LineRelay2\fP, \fBmosh::control::MoveAlongWall\fP и \fBmosh::control::Sync\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBtick\fP () const"
.br
.RI "Обновление системы "
.in -1c
.SH "Подробное описание"
.PP 
Абстрактный исполнитель движения робота 
.SH "Методы"
.PP 
.SS "void Mover::tick () const\fR [virtual]\fP"

.PP
Обновление системы 
.PP
Переопределяется в \fBmosh::control::KeepSpeed\fP, \fBmosh::control::Sync\fP, \fBmosh::control::LineProp\fP, \fBmosh::control::LineRelay\fP, \fBmosh::control::LineRelay2\fP и \fBmosh::control::MoveAlongWall\fP\&..PP
.nf
7 {};
.fi


.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
