.TH "src/hardware/motorencoder.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hardware/motorencoder.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include 'core/config\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmosh::hardware::MotorEncoder\fP"
.br
.RI "класс DC-мотор-энкодера, управляемого H-мостом "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::hardware\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBmosh::hardware::__l_int\fP ()"
.br
.RI "Обработчик левого мотора "
.ti -1c
.RI "void \fBmosh::hardware::__r_int\fP ()"
.br
.RI "Обработчик правого мотора "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
