.TH "src/control/move.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/control/move.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include 'core/enviroment\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmosh::control::Mover\fP"
.br
.RI "Абстрактный исполнитель движения робота "
.ti -1c
.RI "class \fBmosh::control::KeepSpeed\fP"
.br
.RI "режим постоянной скорости "
.ti -1c
.RI "class \fBmosh::control::Sync\fP"
.br
.RI "Синхронизированое движение моторов "
.ti -1c
.RI "class \fBmosh::control::LineProp\fP"
.br
.RI "Пропорциональный регулятор движения по линии "
.ti -1c
.RI "class \fBmosh::control::LineRelay\fP"
.br
.ti -1c
.RI "class \fBmosh::control::LineRelay2\fP"
.br
.RI "Релейный регулятор движения по линии по двум датчикам "
.ti -1c
.RI "class \fBmosh::control::MoveAlongWall\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::control\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
