.TH "src/control/quit.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/control/quit.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'core/enviroment\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmosh::control::Quiter\fP"
.br
.RI "Интерфейс обработки завершения движения "
.ti -1c
.RI "class \fBmosh::control::OnTimer\fP"
.br
.RI "Обработка выхода по таймеру "
.ti -1c
.RI "class \fBmosh::control::DistanceRead\fP"
.br
.RI "Обработка расстояния "
.ti -1c
.RI "class \fBmosh::control::DistanceMoved\fP"
.br
.RI "Было пройдено расстояние "
.ti -1c
.RI "class \fBmosh::control::LineFound\fP"
.br
.RI "Найден перекрёсток "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::control\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
