.TH "RobotConfig" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RobotConfig \- Данные робота  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <enviroment\&.hpp>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBmosh::hardware::DistanceSensor\fP * \fBdist_left\fP = &\fBno_sensor\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::DistanceSensor\fP * \fBdist_right\fP = &\fBno_sensor\fP"
.br
.ti -1c
.RI "\fBmosh::hardware::DistanceSensor\fP * \fBdist_front\fP = &\fBno_sensor\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Данные робота 
.SH "Данные класса"
.PP 
.SS "\fBmosh::hardware::DistanceSensor\fP* RobotConfig::dist_front = &\fBno_sensor\fP"

.SS "\fBmosh::hardware::DistanceSensor\fP* RobotConfig::dist_left = &\fBno_sensor\fP"

.SS "\fBmosh::hardware::DistanceSensor\fP* RobotConfig::dist_right = &\fBno_sensor\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
