.TH "src/core/run.hpp" 3 "MoshLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/run.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <Arduino\&.h>\fP
.br
\fR#include 'control/move\&.hpp'\fP
.br
\fR#include 'control/quit\&.hpp'\fP
.br

.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmosh\fP"
.br
.ti -1c
.RI "namespace \fBmosh::run\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBmosh::run::base\fP (const \fBmosh::control::Mover\fP &mover, const \fBmosh::control::Quiter\fP &quiter, bool hold_at_end=true)"
.br
.RI "Запустить выполнение задачи "
.ti -1c
.RI "void \fBmosh::run::time\fP (const \fBmosh::control::Mover\fP &mover, uint32_t runtime)"
.br
.RI "Выполнение задачи в течении времени "
.ti -1c
.RI "void \fBmosh::run::speed\fP (int8_t speed, const \fBmosh::control::Quiter\fP &quiter)"
.br
.RI "Запустить независимое вращение моторов с заданой скоростью с проверкой "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для MoshLib из исходного текста\&.
